-- MySQL Script generated by MySQL Workbench
-- Wed Sep 21 13:08:15 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema escenario2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema escenario2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `escenario2` DEFAULT CHARACTER SET utf8 ;
USE `escenario2` ;

-- -----------------------------------------------------
-- Table `escenario2`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escenario2`.`roles` (
  `id` INT NOT NULL,
  `rol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escenario2`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escenario2`.`empleados` (
  `id` INT NOT NULL,
  `rolID` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `dni` INT NOT NULL,
  `sueldo` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_empleados_roles_idx` (`rolID` ASC) VISIBLE,
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC) VISIBLE,
  CONSTRAINT `fk_empleados_roles`
    FOREIGN KEY (`rolID`)
    REFERENCES `escenario2`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escenario2`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escenario2`.`categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escenario2`.`articulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escenario2`.`articulos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `price` INT NULL,
  `descripcion` TEXT NULL,
  `stok` INT NULL,
  `categoriasID` INT NOT NULL,
  `visible` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_articulos_categorias_idx` (`categoriasID` ASC) VISIBLE,
  CONSTRAINT `fk_articulos_categorias`
    FOREIGN KEY (`categoriasID`)
    REFERENCES `escenario2`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escenario2`.`mediosDePagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escenario2`.`mediosDePagos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `medio` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escenario2`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escenario2`.`ventas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `articulosID` INT NOT NULL,
  `mediosDePagosID` INT NULL,
  `totalDeCompras` INT NULL,
  `comicion` INT NULL,
  `empleadoID` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ventas_empleados_idx` (`empleadoID` ASC) VISIBLE,
  INDEX `fk_ventas_mediosDePagos_idx` (`mediosDePagosID` ASC) VISIBLE,
  INDEX `fk_ventas_articulos_idx` (`articulosID` ASC) VISIBLE,
  CONSTRAINT `fk_ventas_empleados`
    FOREIGN KEY (`empleadoID`)
    REFERENCES `escenario2`.`empleados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_mediosDePagos`
    FOREIGN KEY (`mediosDePagosID`)
    REFERENCES `escenario2`.`mediosDePagos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_articulos`
    FOREIGN KEY (`articulosID`)
    REFERENCES `escenario2`.`articulos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
