-- MySQL Script generated by MySQL Workbench
-- Wed Sep 21 13:07:23 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema escenario1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema escenario1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `escenario1` DEFAULT CHARACTER SET utf8 ;
USE `escenario1` ;

-- -----------------------------------------------------
-- Table `escenario1`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escenario1`.`categoria` (
  `id` INT NOT NULL,
  `estudiantes` VARCHAR(45) NULL,
  `docentes` VARCHAR(45) NULL,
  `administradores/editores` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escenario1`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escenario1`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `contrasenia` VARCHAR(255) NOT NULL,
  `categoriaID` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `idCategorias_idx` (`categoriaID` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_categorias`
    FOREIGN KEY (`categoriaID`)
    REFERENCES `escenario1`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escenario1`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escenario1`.`cursos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `descripcion` TEXT NOT NULL,
  `imagen` TEXT NOT NULL,
  `fecha_inicio` DATE NULL,
  `fecha_final` DATE NULL,
  `cupo_maximo` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escenario1`.`unidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escenario1`.`unidades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `cursoID` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idCurso_idx` (`cursoID` ASC) VISIBLE,
  CONSTRAINT `idCurso`
    FOREIGN KEY (`cursoID`)
    REFERENCES `escenario1`.`cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escenario1`.`usuarios-cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escenario1`.`usuarios-cursos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuarioID` INT NOT NULL,
  `cursoID` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cursos_usuarios_idx` (`cursoID` ASC) VISIBLE,
  INDEX `fk_usuarios_cursos_idx` (`usuarioID` ASC) VISIBLE,
  CONSTRAINT `fk_cursos_usuarios`
    FOREIGN KEY (`cursoID`)
    REFERENCES `escenario1`.`cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_cursos`
    FOREIGN KEY (`usuarioID`)
    REFERENCES `escenario1`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escenario1`.`clases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escenario1`.`clases` (
  `id` INT NOT NULL,
  `titulo` VARCHAR(45) NULL,
  `fecha_inicio` DATE NULL,
  `visible` TINYINT NULL DEFAULT 0,
  `unidadID` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_clases_unidades_idx` (`unidadID` ASC) VISIBLE,
  CONSTRAINT `fk_clases_unidades`
    FOREIGN KEY (`unidadID`)
    REFERENCES `escenario1`.`unidades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escenario1`.`tipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escenario1`.`tipos` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escenario1`.`bloques`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escenario1`.`bloques` (
  `id` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `visible` TINYINT NULL,
  `tipoID` INT NULL,
  `contenido` VARCHAR(45) NULL,
  `clasesID` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bloques_tipos_idx` (`tipoID` ASC) VISIBLE,
  INDEX `fk:bloques_clases_idx` (`clasesID` ASC) VISIBLE,
  CONSTRAINT `fk_bloques_tipos`
    FOREIGN KEY (`tipoID`)
    REFERENCES `escenario1`.`tipos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk:bloques_clases`
    FOREIGN KEY (`clasesID`)
    REFERENCES `escenario1`.`clases` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
